### ISSUE TITLE
Retroalimentacion Clon de pinterest

### ISSUE THREAD

**Issue by Guirdo** [Angiekdena/PinterestClone#1]
Buen trabajo!

Como recomendación para que sigas mejorando en CSS, en las siguientes lineas:

```css
#navbar-pinterest > * {
  margin-left: 16px;
  margin-right: 16px;
}
```

Puedes agregar el margen horizontal, ya sea para el lado izquierdo y derecho, con una sola propiedad:

```css
#navbar-pinterest > * {
  margin-inline: 16px;
}
```

Te dejo un [articulo](https://lenguajecss.com/css/modelo-de-cajas/propiedades-logicas-css/) que habla sobre con más detalles sobre estas propiedades lógicas.
